FROM openjdk:11
LABEL maintainer="chrisio"
ADD target/neighborhood_doctors-0.0.1-SNAPSHOT.jar neighborhood_doctors-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","neighborhood_doctors-0.0.1-SNAPSHOT.jar"]