name: Flutter Build

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]

jobs:
  build-apk:
    only:
      changes:
        - FrontEnd/*
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FrontEnd/neighborhood_doctor
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.0'
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter build apk --debug
  build-web:
    only:
      changes:
        - FrontEnd/*
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FrontEnd/neighborhood_doctor
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.0'
          channel: stable 
      - name: Build web
        run: |
          flutter pub get
          flutter build web